services:
  - type: web
    runtime: python
    name: arotec-web
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: arotec-members-db
          property: connectionString
      - key: AROTEC_ADMIN_PASSWORD
        sync: false

databases:
  - name: arotec-members-db
    plan: free
